apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::015601052302:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-A0GbRnknYOj1
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::015601052302:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2024-10-14T17:49:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1300"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: dc3c35e5-4672-4454-a588-66d3b9e7c77c